name: Portfolio Deployment
run-name: ${{ github.actor }} triggered the portfolio deployment

on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Write .env file
        run: |
          echo '${{ secrets.ENV_PRODUCTION }}' > .env
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
